### ISSUE TITLE
Try to make this gem easier to install

### ISSUE THREAD

**Issue by agarie** [ruby-opencv/ruby-opencv#15]
Hi,

I installed the gem (after some configuration problems, but mostly my mistakes) and was wondering why it isn't just a matter of typing `gem install ruby-opencv`.

My point is: computer vision is a very interesting topic and lots of people want to know more about it. It'd be great to use OpenCV and Ruby for it. If there's any way to improve the installation of this gem such that most people can use it, then it should be done.

What are the problems that need to be fixed for this? Also, @ser1zw, are you interested in it?

**Comment by swaps19** [comment]
Hi I tried to install this gem with given instructions. I also installed OpenCV following [this](http://docs.opencv.org/2.4/doc/tutorials/introduction/linux_install/linux_install.html#linux-installation) tutorial.
The only change I did is to change the "CMAKE_INSTALL_PREFIX" directory in command 

> 
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..

I used a custom directory instead. 
I suppose its only the installation directory for OpenCV, so I passed this directory in "--with" option that you have mentioned in the installation guideline.
But its giving an error "Failed to build gem native extension."

What should I suppose to do?
