### ISSUE TITLE
version 0.0.10 does not load under windows (opencv version 2.4.6)

### ISSUE THREAD

**Issue by alor** [ruby-opencv/ruby-opencv#34]
as soon as i try to load the opencv library i get this error:

```
K:\scripts\face>ruby -e "require 'opencv'"
K:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': cannot load such file -- opencv.so (LoadError)
        from K:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
        from K:/Ruby/lib/ruby/gems/1.9.1/gems/ruby-opencv-0.0.10-x86-mingw32/lib/opencv.rb:8:in `rescue in <top (required)>'
        from K:/Ruby/lib/ruby/gems/1.9.1/gems/ruby-opencv-0.0.10-x86-mingw32/lib/opencv.rb:5:in `<top (required)>'
        from K:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `require'
        from K:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:60:in `rescue in require'
        from K:/Ruby/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:35:in `require'
        from -e:1:in `<main>'
```
i've installed OpenCV 2.4.6 binaries from its site and correctly set the PATH to the mingw/bin directory

opencv.so file is present in 1.9/ directory.

ruby version is:
ruby 1.9.3p429 (2013-05-15) [i386-mingw32]

operating system is: 
Windows 7 64bit

gem is:
ruby-opencv (0.0.10 i386-mingw32)

which version of OpenCV was used to build the gem? i'm using 2.4.6 since 2.4.6.1 is not available for download.

how can i solve the problem?

thank you

**Comment by ser1zw** [comment]
Added a document for installation on Windows. See https://github.com/ruby-opencv/ruby-opencv/blob/master/install-ruby-opencv-with-rubyinstaller-on-windows.md .
