### ISSUE TITLE
nonfree.hpp not found

### ISSUE THREAD

**Issue by pammacdotnet** [ruby-opencv/ruby-opencv#43]
Them "gem install" process could not find opencv2/nonfree/nonfree.hpp (just this single file). Very very weird given the file (nonfree.hpp) was present in the mentioned path (as all other header files).

I removed the reference to nonfree.hpp from extconf.rb, rake gem, and the installed the resulting gem. Worked flawlessly.

gem install pkg/ruby-opencv-0.0.11.gem -- --with-opencv-dir=/Users/pammac/Homebrew/Cellar/opencv/2.4.7.1

checking for opencv2/core/core.hpp... yes
checking for opencv2/imgproc/imgproc_c.h... yes
checking for opencv2/imgproc/imgproc.hpp... yes
checking for opencv2/video/tracking.hpp... yes
checking for opencv2/features2d/features2d.hpp... yes
checking for opencv2/flann/flann.hpp... yes
checking for opencv2/calib3d/calib3d.hpp... yes
checking for opencv2/objdetect/objdetect.hpp... yes
checking for opencv2/legacy/compat.hpp... yes
checking for opencv2/legacy/legacy.hpp... yes
checking for opencv2/highgui/highgui_c.h... yes
checking for opencv2/highgui/highgui.hpp... yes
checking for opencv2/photo/photo.hpp... yes
checking for opencv2/nonfree/nonfree.hpp... no

**Comment by yshahin** [comment]
should this be closed?

**Comment by ser1zw** [comment]
Yes, thank you @yshahin .
