### ISSUE TITLE
Library Not found

### ISSUE THREAD

**Issue by pratik14** [ruby-opencv/ruby-opencv#46]
$ gem install ruby-opencv
Fetching: ruby-opencv-0.0.12.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing ruby-opencv:
ERROR: Failed to build gem native extension.

    /home/admin/.rvm/rubies/ruby-1.9.3-p484/bin/ruby extconf.rb
Check the required libraries...
checking for main() in -lopencv_calib3d... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/admin/.rvm/rubies/ruby-1.9.3-p484/bin/ruby
	--with-opencv-dir
	--without-opencv-dir
	--with-opencv-include
	--without-opencv-include=${opencv-dir}/include
	--with-opencv-lib
	--without-opencv-lib=${opencv-dir}/lib
	--with-libxml2-dir
	--without-libxml2-dir
	--with-libxml2-include
	--without-libxml2-include=${libxml2-dir}/include
	--with-libxml2-lib
	--without-libxml2-lib=${libxml2-dir}/lib
	--with-opencv_calib3dlib
	--without-opencv_calib3dlib
extconf.rb:53:in `block in <main>': libopencv_calib3d not found. (RuntimeError)
	from extconf.rb:52:in `each'
	from extconf.rb:52:in `<main>'

**Comment by acearth** [comment]
Before you execute `brew install opencv`, you need to add science repo.
```
brew tap homebrew/science
```
