### ISSUE TITLE
Cannot compile in Ubuntu 12.04

### ISSUE THREAD

**Issue by omjokine** [ruby-opencv/ruby-opencv#50]
I'm using Ubuntu 12.04 and libopencv2.4 from raring (13.04) repositories. Compiling fails errors on algorithm.cpp. I also tried to compile opencv manually, but got same error. 

Here's output:
>> Check the required libraries...
checking for main() in -lstdc++... yes
checking for main() in -lopencv_calib3d... yes
checking for main() in -lopencv_contrib... yes
checking for main() in -lopencv_core... yes
checking for main() in -lopencv_features2d... yes
checking for main() in -lopencv_flann... yes
checking for main() in -lopencv_highgui... yes
checking for main() in -lopencv_imgproc... yes
checking for main() in -lopencv_legacy... yes
checking for main() in -lopencv_ml... yes
checking for main() in -lopencv_objdetect... yes
checking for main() in -lopencv_video... yes
checking for main() in -lopencv_photo... yes
checking for main() in -lopencv_gpu... no
opencv_gpu not found.
checking for main() in -lopencv_nonfree... no
opencv_nonfree not found.
>> Check the required headers...
checking for opencv2/core/core_c.h... yes
checking for opencv2/core/core.hpp... yes
checking for opencv2/imgproc/imgproc_c.h... yes
checking for opencv2/imgproc/imgproc.hpp... yes
checking for opencv2/video/tracking.hpp... yes
checking for opencv2/features2d/features2d.hpp... yes
checking for opencv2/flann/flann.hpp... yes
checking for opencv2/calib3d/calib3d.hpp... yes
checking for opencv2/objdetect/objdetect.hpp... yes
checking for opencv2/legacy/compat.hpp... yes
checking for opencv2/legacy/legacy.hpp... yes
checking for opencv2/highgui/highgui_c.h... yes
checking for opencv2/highgui/highgui.hpp... yes
checking for opencv2/photo/photo.hpp... yes
checking for opencv2/nonfree/nonfree.hpp... no
opencv2/nonfree/nonfree.hpp not found.
checking for stdarg.h... yes
creating Makefile

make  clean

make
compiling cvavgcomp.cpp
compiling cvconvexitydefect.cpp
compiling cvmoments.cpp
compiling cvconnectedcomp.cpp
compiling cvvideowriter.cpp
compiling facerecognizer.cpp
compiling cvmat.cpp
cvmat.cpp: In function ‘VALUE mOpenCV::cCvMat::rb_subspace_reconstruct(VALUE, VALUE, VALUE)’:
cvmat.cpp:5702:10: warning: ‘result’ may be used uninitialized in this function [-Wuninitialized]
cvmat.cpp: In function ‘VALUE mOpenCV::cCvMat::rb_subspace_project(VALUE, VALUE, VALUE)’:
cvmat.cpp:5678:10: warning: ‘projection’ may be used uninitialized in this function [-Wuninitialized]
cvmat.cpp: In function ‘VALUE mOpenCV::cCvMat::rb_apply_color_map(VALUE, VALUE)’:
cvmat.cpp:5145:10: warning: ‘dst’ may be used uninitialized in this function [-Wuninitialized]
cvmat.cpp: In function ‘VALUE mOpenCV::cCvMat::rb_normalize(int, VALUE*, VALUE)’:
cvmat.cpp:2141:10: warning: ‘dst’ may be used uninitialized in this function [-Wuninitialized]
compiling pointset.cpp
pointset.cpp: In function ‘CvSeq* mOpenCV::VALUE_TO_POINT_SET(VALUE)’:
pointset.cpp:245:9: warning: variable ‘tmp’ set but not used [-Wunused-but-set-variable]
pointset.cpp:246:7: warning: variable ‘length’ set but not used [-Wunused-but-set-variable]
compiling cvutils.cpp
compiling eigenfaces.cpp
compiling cvseq.cpp
compiling lbph.cpp
compiling cvhistogram.cpp
compiling fisherfaces.cpp
compiling cvfont.cpp
compiling cvtwopoints.cpp
compiling iplimage.cpp
compiling window.cpp
compiling trackbar.cpp
compiling cvhumoments.cpp
compiling cvfeaturetree.cpp
compiling cvsurfparams.cpp
cvsurfparams.cpp: In function ‘VALUE mOpenCV::cCvSURFParams::new_object(CvSURFParams*)’:
cvsurfparams.cpp:172:17: warning: variable ‘ptr’ set but not used [-Wunused-but-set-variable]
compiling cvline.cpp
compiling cverror.cpp
compiling cvcontourtree.cpp
compiling cvslice.cpp
compiling cvchain.cpp
compiling gui.cpp
compiling cvmemstorage.cpp
compiling iplconvkernel.cpp
compiling algorithm.cpp
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_int(VALUE, VALUE, VALUE)’:
algorithm.cpp:32:22: error: ‘class cv::Algorithm’ has no member named ‘setInt’
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_double(VALUE, VALUE, VALUE)’:
algorithm.cpp:46:22: error: ‘class cv::Algorithm’ has no member named ‘setDouble’
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_bool(VALUE, VALUE, VALUE)’:
algorithm.cpp:61:22: error: ‘class cv::Algorithm’ has no member named ‘setBool’
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_string(VALUE, VALUE, VALUE)’:
algorithm.cpp:76:22: error: ‘class cv::Algorithm’ has no member named ‘setString’
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_mat(VALUE, VALUE, VALUE)’:
algorithm.cpp:92:22: error: ‘class cv::Algorithm’ has no member named ‘setMat’
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_matvector(VALUE, VALUE, VALUE)’:
algorithm.cpp:115:22: error: ‘class cv::Algorithm’ has no member named ‘setMatVector’
algorithm.cpp: In function ‘VALUE mOpenCV::cAlgorithm::rb_set_algorithm(VALUE, VALUE, VALUE)’:
algorithm.cpp:129:22: error: ‘class cv::Algorithm’ has no member named ‘setAlgorithm’
make: *** [algorithm.o] Error 1

make failed, exit code 2

**Comment by ser1zw** [comment]
Fixed.
