### ISSUE TITLE
missing norm (rb_norm) method

### ISSUE THREAD

**Issue by chomzy** [ruby-opencv/ruby-opencv#59]
Hi,

I'm :mag: looking for norm method which is available with OpenCV.
http://docs.opencv.org/modules/core/doc/operations_on_arrays.html#norm

I have found that commented out line in `ext/opencv/cvmat.h`. Is there any specific reason to disable norm method for ruby-opencv?

ext/opencv/cvmat.h 

//VALUE rb_norm();

If not please make it available. :smile:

**Comment by ser1zw** [comment]
Hi,

sorry for the late reply.
I added CvMat#norm at eb61e5f183f492a7514896d75f54eb65c2b32c1e .

This will be included in the next release.
