### ISSUE TITLE
match_shapes for contours

### ISSUE THREAD

**Issue by jarek-railwaymen** [ruby-opencv/ruby-opencv#61]
Shouldn't match_shapes method be defined for instances of OpenCV::CvContour? In opencv for example two contour objects can be compared http://docs.opencv.org/modules/imgproc/doc/structural_analysis_and_shape_descriptors.html?highlight=cvmatchshapes#matchshapes I think it is now not possible using ruby-opencv

**Comment by ser1zw** [comment]
You are right. `match_shapes` should also be defined for `CvContour`'s instances.
In current ruby-opencv, the method is defined for `CvMat` just because of a historical reason.
I'll fix it.
