### ISSUE TITLE
Safe for Sidekiq / threadsafe?

### ISSUE THREAD

**Issue by the911s** [ruby-opencv/ruby-opencv#62]
This is more of a question than an issue:

We were running our code as a background job in [Resque](https://github.com/resque/resque), but are hoping to switch to [Sidekiq](https://github.com/mperham/sidekiq). Sidekiq requires that all code running within a job is threadsafe. Should we expect code using ruby-opencv to be threadsafe?

By the way, thank you for a great library! We've used it to process millions of jobs.

Thanks!

**Comment by ser1zw** [comment]
Thanks for using ruby-opencv!

Unfortunately, this library is not thread safe.
For historical reasons, it is not designed with thread safety...

**Comment by the911s** [comment]
Thanks for the response. Keep up the good work! Closing this issue...
