### ISSUE TITLE
Do not support windows with opencv2.4

### ISSUE THREAD

**Issue by WoolenWang** [ruby-opencv/ruby-opencv#66]
When i add the opencv dev lib to path for example 
E:\ruby\opencv_2.4\opencv\build\x86\vc10\bin

and then i try cmd : opencv_createsamples.exe it print out the basic info like 
C:\Users\Administrator>opencv_createsamples.exe
Usage: opencv_createsamples.exe
  [-info <collection_file_name>]
  [-img <image_file_name>]
  [-vec <vec_file_name>]
  [-bg <background_file_name>]
  [-num <number_of_samples = 1000>]
  [-bgcolor <background_color = 0>]
  [-inv] [-randinv] [-bgthresh <background_color_threshold = 80>]
  [-maxidev <max_intensity_deviation = 40>]
  [-maxxangle <max_x_rotation_angle = 1.100000>]
  [-maxyangle <max_y_rotation_angle = 1.100000>]
  [-maxzangle <max_z_rotation_angle = 0.500000>]
  [-show [<scale = 4.000000>]]
  [-w <sample_width = 24>]
  [-h <sample_height = 24>]
  [-pngoutput]

and then i try to gem install ruby-opencv it turn out  fail and the output is like 

extconf.rb:22:in `initialize': No such file or directory - /usr/local/include/opencv2/core/version.hpp (Errno::ENOENT)
        from extconf.rb:22:in `open'
        from extconf.rb:22:in `cv_version_suffix'
        from extconf.rb:53:in `<main>'

check the extconf.rb it write the dir_config with dir_config("libxml2", "/usr/include", "/usr/lib")
this turn out to fail when try  open(File.expand_path(File.join(incdir, 'opencv2','core','version.hpp')), 'r') { |f|

after i fix the extconf.rb with my own opencv env, it can success generate makfile and success make

please fix to adjust windows platform so that we can use this usefull gem, thanks

**Comment by PezCoder** [comment]
How should i modify extconfi.rb & where is it available? I am having the same issue.

**Comment by ser1zw** [comment]
Hi,

Sorry for the late reply.

Try the following command with the parameters `--with-opencv-include`(specify the header file directory, where `version.hpp` is located) and `--with-opencv-lib`(specify the library directory).
```
gem install ruby-opencv -- --with-opencv-include=E:\ruby\opencv_2.4\opencv\build\include --with-opencv-lib=E:\ruby\opencv_2.4\opencv\build\x86\vc10\lib
```
https://github.com/ruby-opencv/ruby-opencv/blob/master/DEVELOPERS_NOTE.md#windows-mswin32

On Windows, the location where OpenCV installed is vary from person to person.
So we need to specify the paths because `extconf.rb` can't search the directories automatically.

**Comment by PezCoder** [comment]
Thanks for help.. But it's still failing for me. Never mind !

**Comment by linyuansen** [comment]
lysc6@lysc6-PC MINGW64 /d/lysc6/Desktop
$ gem install ruby-opencv -- --with-opencv-include=D:/gsoft/opencv/build/includ
e --with-opencv-lib=D:/gsoft/opencv/build/x64/vc11/lib
Building native extensions with: '--with-opencv-include=D:/gsoft/opencv/build/in
clude --with-opencv-lib=D:/gsoft/opencv/build/x64/vc11/lib'
This could take a while...
ERROR:  Error installing ruby-opencv:
        ERROR: Failed to build gem native extension.

    D:/Ruby22-x64/bin/ruby.exe extconf.rb --with-opencv-include=D:/gsoft/opencv/
build/include --with-opencv-lib=D:/gsoft/opencv/build/x64/vc11/lib
>> Check the required libraries...
checking for main() in -lmsvcrt... yes
checking for main() in -lopencv_calib3d2413... yes
checking for main() in -lopencv_contrib2413... yes
checking for main() in -lopencv_core2413... yes
checking for main() in -lopencv_features2d2413... yes
checking for main() in -lopencv_flann2413... yes
checking for main() in -lopencv_highgui2413... yes
checking for main() in -lopencv_imgproc2413... yes
checking for main() in -lopencv_legacy2413... yes
checking for main() in -lopencv_ml2413... yes
checking for main() in -lopencv_objdetect2413... yes
checking for main() in -lopencv_video2413... yes
checking for main() in -lopencv_photo2413... yes
checking for main() in -lopencv_gpu2413... yes
checking for main() in -lopencv_nonfree2413... yes
>> Check the required headers...
checking for opencv2/core/core_c.h... yes
checking for opencv2/core/core.hpp... yes
checking for opencv2/imgproc/imgproc_c.h... yes
checking for opencv2/imgproc/imgproc.hpp... yes
checking for opencv2/video/tracking.hpp... yes
checking for opencv2/features2d/features2d.hpp... yes
checking for opencv2/flann/flann.hpp... yes
checking for opencv2/calib3d/calib3d.hpp... yes
checking for opencv2/objdetect/objdetect.hpp... yes
checking for opencv2/legacy/compat.hpp... yes
checking for opencv2/legacy/legacy.hpp... yes
checking for opencv2/highgui/highgui_c.h... yes
checking for opencv2/highgui/highgui.hpp... yes
checking for opencv2/photo/photo.hpp... yes
checking for opencv2/nonfree/nonfree.hpp... yes
checking for stdarg.h... yes
creating Makefile

make "DESTDIR=" clean
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

make "DESTDIR="
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

make failed, exit code 1

Gem files will remain installed in D:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/ruby-o
pencv-0.0.16 for inspection.
Results logged to D:/Ruby22-x64/lib/ruby/gems/2.2.0/extensions/x64-mingw32/2.2.0
/ruby-opencv-0.0.16/gem_make.out

**Comment by ser1zw** [comment]
Added a document for installation on Windows. See https://github.com/ruby-opencv/ruby-opencv/blob/master/install-ruby-opencv-with-rubyinstaller-on-windows.md .
