### ISSUE TITLE
Installing the experimental/opencv3 branch

### ISSUE THREAD

**Issue by ryan-robeson** [ruby-opencv/ruby-opencv#77]
Hey, I decided to use OpenCV for the first time this weekend on a personal project. I saw that your library has experimental support for OpenCV3, so I decided to start there. I had a couple small problems installing the experimental branch, but I got them resolved and thought I should share. All I've really used is the face detection, but it's working great for my purposes. Thanks for the awesome library! 

I apologize in advance if you're already aware of these issues or I missed something simple.

The first problem was that Bundler refused to build the native extension with the symlink to OpenCV3 that was invalid on my system. Removing `/ext/opencv/opencv-3.1.0` was easy enough.

The other issue was that extconf kept failing because it wasn't building the headers with C++. Maybe this problem is specific to my setup? After some googling, I found that wrapping the headers line in a `with_cflags` block solved the problem. I don't have any experience with writing native extensions, so there's probably a better way to do it. But, it got things working for me.

```ruby
with_cflags("-x c++") do
  opencv_headers.each { |header| raise "#{header} not found." unless have_header(header) }
end
```

**Comment by ser1zw** [comment]
Hi,

Thanks for your comment!

The first problem is my mistake of ```.gitignore```, so I'll fix it.

The second one might be environment-specific.
The ```extconf.rb``` sets compile options using ```RbConfig::CONFIG``` and ```RbConfig::MAKEFILE_CONFIG```,
but they might not work in some cases.

Your code looks good and also works for me (Ubuntu 16.04, gcc/g++ 5.3.1, ruby 2.3.1), so I'll add your fix and check it in some environments.

What OS, C/C++ compiler and ruby version are you using?

**Comment by ryan-robeson** [comment]
No problem.

Ok, great. 

I'm on OS X 10.9.5, clang 600.0.57, ruby 2.1.2p95

```bash
bash:# cc -v                                 
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix
```

**Comment by ser1zw** [comment]
Thanks!
