### ISSUE TITLE
Problems building on Ruby 2.4 (Fixnums!)

### ISSUE THREAD

**Issue by epitron** [ruby-opencv/ruby-opencv#88]
The compiler is failing to build a couple of files which use `rb_cFixnum` types directly (`cvchain.cpp` and `cvseq.cpp`).

I tried changing the `rb_cFixnum`s to `rb_cInteger`s, and it builds properly now. The test output is pretty spammy though, so I'm not sure if everything is working.

(`Fixnum`s are still being used in the Ruby code, but it just throws lots of deprecation warnings).

**Comment by ser1zw** [comment]
I just merged a PR ( https://github.com/ruby-opencv/ruby-opencv/pull/87 ) which probably fixes the problem.
I'll check the details and release the new version later.

**Comment by epitron** [comment]
Excellent! Thanks.

**Comment by ser1zw** [comment]
Fixed in v0.0.18
