### ISSUE TITLE
installation error using opencv 3.3.1-dev

### ISSUE THREAD

**Issue by aoreinoso** [ruby-opencv/ruby-opencv#96]
git clone https://github.com/opencv/opencv_contrib.git
git clone https://github.com/opencv/opencv.git

cd opencv_contrib/
mkdir make_dir
cd make_dir/
cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -DOPENCV_EXTRA_MODULES_PATH=../modules ../../opencv
make -j5
sudo make install

$ opencv_version 
3.3.1-dev

sudo gem install ruby-opencv -- --with-opencv-dir=/usr/local
Building native extensions with: '--with-opencv-dir=/usr/local/'
This could take a while...
ERROR:  Error installing ruby-opencv:
	ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.4.0/gems/ruby-opencv-0.0.18/ext/opencv
/usr/local/bin/ruby -r ./siteconf20171103-9923-nmpozw.rb extconf.rb --with-opencv-dir=/usr/local/
>> Check the required libraries...
checking for -lstdc++... yes
checking for -lopencv_calib3d... yes
checking for -lopencv_contrib... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/local/bin/$(RUBY_BASE_NAME)
	--with-opencv-dir
	--with-opencv-include
	--without-opencv-include=${opencv-dir}/include
	--with-opencv-lib
	--without-opencv-lib=${opencv-dir}/lib
	--with-libxml2-dir
	--without-libxml2-dir
	--with-libxml2-include
	--without-libxml2-include=${libxml2-dir}/include
	--with-libxml2-lib
	--without-libxml2-lib=${libxml2-dir}/lib
	--with-stdc++lib
	--without-stdc++lib
	--with-opencv_calib3dlib
	--without-opencv_calib3dlib
	--with-opencv_contriblib
	--without-opencv_contriblib
extconf.rb:58:in `block in <main>': opencv_contrib not found. (RuntimeError)
	from extconf.rb:58:in `each'
	from extconf.rb:58:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /usr/local/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/ruby-opencv-0.0.18/mkmf.log

extconf failed, exit code 1

**Comment by ser1zw** [comment]
For now ruby-opencv does not support OpenCV 3.x, so please try with OpenCV 2.4.
(I am working on developing OpenCV 3.x ver. in other branch https://github.com/ruby-opencv/ruby-opencv/tree/experimental/opencv3 , but it does not have enough functions yet)

Sorry for the inconvenience.

**Comment by aoreinoso** [comment]
Thank you
